# Generated by Aurora-X v3 (offline, safe)
def create_hello_world_function() -> str:
    """Generate creative text output."""
    return f"Creative output generated for: {description or 'your request'}"
