# Generated by Aurora-X v3 (offline, safe)
def max_in_list(nums: list[int]) -> int:
    """Return the largest number in a list."""
    if not nums:
        raise ValueError("List cannot be empty")
    return max(nums)
