# Aurora-X Maritime Deployment (Boats, Ships, Submarines)
version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.edge
    image: ghcr.io/chango112595-cell/Aurora-x:maritime
    container_name: aurora-x-maritime
    ports:
      - "${PORT:-8000}:8000"
    environment:
      AURORA_TOKEN_SECRET: ${AURORA_TOKEN_SECRET}
      ENVIRONMENT: ${ENVIRONMENT:-maritime}
      MARITIME_MODE: "true"
      NMEA_ENABLED: "true"
      PYTHONUNBUFFERED: "1"
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8000/healthz"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
