"""
Decryption Program
Generated by Aurora-X from natural language request
"""

from typing import Dict, List, Tuple, Optional, Any, Union



def decrypt_caesar(ciphertext: str, shift: int) -> str:
    """
    Decrypt a Caesar cipher with given shift.

    Args:
        ciphertext: The encrypted text
        shift: Number of positions to shift back

    Returns:
        The decrypted plaintext
    """
    result = []
    for char in ciphertext:
        if char.isalpha():
            ascii_offset = 65 if char.isupper() else 97
            decrypted_char = chr((ord(char) - ascii_offset - shift) % 26 + ascii_offset)
            result.append(decrypted_char)
        else:
            result.append(char)
    return "".join(result)


def decrypt_substitution(ciphertext: str, key: dict) -> str:
    """
    Decrypt a substitution cipher using the provided key.

    Args:
        ciphertext: The encrypted text
        key: Dictionary mapping encrypted chars to plaintext chars

    Returns:
        The decrypted plaintext
    """
    result = []
    for char in ciphertext:
        result.append(key.get(char, char))
    return "".join(result)


def decrypt_vigenere(ciphertext: str, keyword: str) -> str:
    """
    Decrypt a Vigenre cipher using the provided keyword.

    Args:
        ciphertext: The encrypted text
        keyword: The decryption keyword

    Returns:
        The decrypted plaintext
    """
    result = []
    keyword_repeated = (keyword * (len(ciphertext) // len(keyword) + 1))[: len(ciphertext)]

    for i, char in enumerate(ciphertext):
        if char.isalpha():
            ascii_offset = 65 if char.isupper() else 97
            shift = ord(keyword_repeated[i].upper()) - 65
            decrypted_char = chr((ord(char) - ascii_offset - shift) % 26 + ascii_offset)
            result.append(decrypted_char)
        else:
            result.append(char)

    return "".join(result)


def main():
    """Interactive decryption program"""
    print("[EMOJI] Decryption Program by Aurora-X")
    print("=" * 50)
    print("\nAvailable methods:")
    print("1. Caesar Cipher")
    print("2. Substitution Cipher")
    print("3. Vigenre Cipher")

    choice = input("\nSelect method (1-3): ").strip()
    ciphertext = input("Enter encrypted text: ").strip()

    if choice == "1":
        shift = int(input("Enter shift value (1-25): "))
        plaintext = decrypt_caesar(ciphertext, shift)
        print(f"\n[OK] Decrypted: {plaintext}")

    elif choice == "2":
        print("Enter substitution key (e.g., A:Z,B:Y,C:X...)")
        key_input = input("Key: ").strip()
        key = dict(pair.split(":") for pair in key_input.split(","))
        plaintext = decrypt_substitution(ciphertext, key)
        print(f"\n[OK] Decrypted: {plaintext}")

    elif choice == "3":
        keyword = input("Enter keyword: ").strip()
        plaintext = decrypt_vigenere(ciphertext, keyword)
        print(f"\n[OK] Decrypted: {plaintext}")

    else:
        print("[ERROR] Invalid choice")


if __name__ == "__main__":
    main()
