services:
  aurora:
    # Build Aurora from your GitHub repo
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: aurora_x
    environment:
      PORT: "8000"
      AURORA_ENV: "prod"
      AURORA_HEALTH_TOKEN: "${AURORA_HEALTH_TOKEN:-ok}"
      AURORA_DISCORD_WEBHOOK: "${AURORA_DISCORD_WEBHOOK:-}"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/health?token=${AURORA_HEALTH_TOKEN:-ok}"]
      interval: 15s
      timeout: 5s
      retries: 20
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: aurora_cf
    depends_on:
      aurora:
        condition: service_healthy
    command: tunnel run
    environment:
      TUNNEL_TOKEN: "${CF_TUNNEL_TOKEN}"
    restart: unless-stopped