"""
Flask web application: Create a Flask web app with dashboard UI
Generated by Aurora-X Synthesis Engine
"""

from flask import Flask, render_template_string, jsonify
import os


HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
            display: flex;
            justify-content: center;
            align-items: center;
            color: #333;
        }
        
        .container {
            background: white;
            border-radius: 12px;
            padding: 2rem;
            box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);
            max-width: 800px;
            width: 90%;
        }
        
        h1 {
            color: #667eea;
            margin-bottom: 1rem;
            font-size: 2rem;
        }
        
        h2 {
            color: #764ba2;
            margin-bottom: 1rem;
        }
        
        p {
            line-height: 1.6;
            color: #666;
        }
        
        nav {
            margin: 2rem 0;
            padding: 1rem 0;
            border-top: 1px solid #e0e0e0;
            border-bottom: 1px solid #e0e0e0;
        }
        
        nav a {
            color: #667eea;
            text-decoration: none;
            margin-right: 1.5rem;
            font-weight: 500;
            transition: color 0.3s ease;
        }
        
        nav a:hover {
            color: #764ba2;
        }
        
        .content {
            margin-top: 2rem;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Aurora Flask Application</h1>
        <nav>
            <a href="/">Home</a>
            <a href="/api/health">API Health</a>
        </nav>
        <div class="content">
            {content|safe}
        </div>
    </div>
</body>
</html>
"""


def create_app() -> Flask:
    """Create and configure the Flask application"""
    app = Flask(__name__)
    app.config['ENV'] = 'development'
    app.config['DEBUG'] = True
    
    @app.route('/dashboard')
    def dashboard():
        """Render dashboard page"""
        return render_template_string(HTML_TEMPLATE.format(
            title="Dashboard - Aurora App",
            content="<h2>Dashboard Page</h2><p>Welcome to the dashboard section.</p>"
        ))
    
    @app.route('/api/health')
    def health():
        """Health check endpoint"""
        return jsonify({"status": "healthy", "app": "Flask Web UI"})
    
    @app.errorhandler(404)
    def not_found(error):
        """Handle 404 errors"""
        return render_template_string(HTML_TEMPLATE.format(
            title="404 - Not Found",
            content="<h2>Page Not Found</h2><p>The requested page could not be found.</p>"
        )), 404
    
    return app


if __name__ == '__main__':
    app = create_app()
    port = int(os.environ.get('PORT', '5000'))
    print(f"🚀 Flask Web App starting on http://localhost:{port}")
    app.run(host='0.0.0.0', port=port, debug=True)
