"""
Aurora Live Status API - Auto-generated by Aurora
Provides real-time server status data for dashboard
"""


def get_live_status():
    """Get current status of all Aurora servers"""
    import subprocess

    servers = {
        "backend": {"port": 5000, "status": "unknown"},
        "bridge": {"port": 5001, "status": "unknown"},
        "self-learn": {"port": 5002, "status": "unknown"},
        "chat": {"port": 5004, "status": "unknown"},
        "vite": {"port": 5173, "status": "unknown"},
    }

    # Check each server
    for name, info in servers.items():
        try:
            result = subprocess.run(
                f"curl -s -o /dev/null -w '%{{http_code}}' http://localhost:{info['port']} --max-time 2",
                shell=True,
                capture_output=True,
                text=True,
                timeout=3,
            )
            status_code = result.stdout.strip()
            info["status"] = "online" if status_code in ["200", "404"] else "offline"
            info["http_code"] = status_code
        except:
            info["status"] = "offline"

    return servers


if __name__ == "__main__":
    import json

    print(json.dumps(get_live_status(), indent=2))
