"""
Flask Application
Create a simple Flask API with user endpoints
Generated by Aurora-X Synthesis Engine
"""

from flask import Flask, render_template, jsonify, request
from flask_cors import CORS
import os
from datetime import datetime
from flask_login import LoginManager

def create_app():
    """Create and configure Flask application"""
    app = Flask(__name__)
    app.config['SECRET_KEY'] = os.environ.get('SECRET_KEY', 'dev-secret-key-change-in-production')
    
    # Enable CORS for API endpoints
    CORS(app)
    
    login_manager = LoginManager(app)
    
    @app.route('/')
    def index():
        """Home page"""
        return jsonify({
            'message': 'Welcome to Create a simple Flask API with user endpoints',
            'timestamp': datetime.utcnow().isoformat(),
            'status': 'running'
        })
    
    @app.route('/health')
    def health_check():
        """Health check endpoint"""
        return jsonify({'status': 'healthy', 'timestamp': datetime.utcnow().isoformat()})
    
    
    
    @app.errorhandler(404)
    def not_found(error):
        return jsonify({'error': 'Not found'}), 404
    
    @app.errorhandler(500)
    def internal_error(error):
        return jsonify({'error': 'Internal server error'}), 500
    
    return app


if __name__ == '__main__':
    app = create_app()
    port = int(os.environ.get('PORT', 8000))
    debug = os.environ.get('DEBUG', 'true').lower() == 'true'
    
    print(f"🚀 Starting Flask application on port {port}...")
    print(f"📝 Description: Create a simple Flask API with user endpoints")
    print(f"🔧 Features: auth, api")
    
    app.run(host='0.0.0.0', port=port, debug=debug)
