# Generated by Aurora-X v3 (offline, safe)
def fibonacci(n: int) -> int:
    """Return n-th Fibonacci number using iterative O(n)."""
    if n < 0: raise ValueError("n must be non-negative")
    a, b = 0, 1
    for _ in range(n):
        a, b = b, a + b
    return a
