import React, { useState, useEffect } from 'react';
import './App.css';

function App() {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    // Fetch initial data
    fetchData();
  }, []);

  const fetchData = async () => {
    try {
      setLoading(true);
      const response = await fetch('/api/');
      if (!response.ok) {
        throw new Error('Failed to fetch data');
      }
      const json = await response.json();
      setData(json);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="App">
      <header className="App-header">
        <h1>Create a calculator</h1>
        <p>Generated by Aurora-X Synthesis Engine</p>
      </header>
      
      <main className="App-main">
        {loading && <div className="loading">Loading...</div>}
        {error && <div className="error">Error: {error}</div>}
        {data && (
          <div className="data-display">
            <pre>{JSON.stringify(data, null, 2)}</pre>
          </div>
        )}
        
        <div className="features">
          <h2>Features</h2>
          <ul>
                        <li>No features specified</li>
          </ul>
        </div>
      </main>
      
      <footer className="App-footer">
        <p>&copy; 2024 Aurora-X Generated Application</p>
      </footer>
    </div>
  );
}

export default App;
