
import { corpusStorage } from "../server/corpus-storage";

// Add comprehensive test entries matching the original corpus
const testEntries = [
  {
    id: "test-entry-1",
    timestamp: new Date().toISOString(),
    spec_id: "test-spec-1",
    spec_hash: "abc123",
    func_name: "add_numbers",
    func_signature: "def add_numbers(a: int, b: int) -> int",
    passed: 5,
    total: 5,
    score: 1.0,
    failing_tests: [],
    snippet: "def add_numbers(a: int, b: int) -> int:\n    return a + b",
    complexity: 1,
    iteration: 1,
    calls_functions: [],
    sig_key: "add_numbers|int,int|int",
    post_bow: ["add", "numbers", "return"],
    duration_ms: 50,
    synthesis_method: "beam_search"
  },
  {
    id: "test-entry-2",
    timestamp: new Date().toISOString(),
    spec_id: "test-spec-2",
    spec_hash: "def456",
    func_name: "reverse_string",
    func_signature: "def reverse_string(s: str) -> str",
    passed: 3,
    total: 3,
    score: 1.0,
    failing_tests: [],
    snippet: "def reverse_string(s: str) -> str:\n    return s[::-1]",
    complexity: 1,
    iteration: 1,
    calls_functions: [],
    sig_key: "reverse_string|str|str",
    post_bow: ["reverse", "string", "return"],
    duration_ms: 45,
    synthesis_method: "beam_search"
  },
  {
    id: "test-entry-3",
    timestamp: new Date().toISOString(),
    spec_id: "test-spec-3",
    spec_hash: "ghi789",
    func_name: "factorial",
    func_signature: "def factorial(n: int) -> int",
    passed: 5,
    total: 5,
    score: 1.0,
    failing_tests: [],
    snippet: "def factorial(n: int) -> int:\n    if n <= 1:\n        return 1\n    return n * factorial(n - 1)",
    complexity: 3,
    iteration: 1,
    calls_functions: [],
    sig_key: "factorial|int|int",
    post_bow: ["factorial", "return"],
    duration_ms: 60,
    synthesis_method: "beam_search"
  },
  {
    id: "test-entry-4",
    timestamp: new Date().toISOString(),
    spec_id: "test-spec-4",
    spec_hash: "jkl012",
    func_name: "is_palindrome",
    func_signature: "def is_palindrome(s: str) -> bool",
    passed: 4,
    total: 4,
    score: 1.0,
    failing_tests: [],
    snippet: "def is_palindrome(s: str) -> bool:\n    return s == s[::-1]",
    complexity: 2,
    iteration: 1,
    calls_functions: [],
    sig_key: "is_palindrome|str|bool",
    post_bow: ["palindrome", "return"],
    duration_ms: 40,
    synthesis_method: "beam_search"
  },
  {
    id: "test-entry-5",
    timestamp: new Date().toISOString(),
    spec_id: "test-spec-5",
    spec_hash: "mno345",
    func_name: "fibonacci",
    func_signature: "def fibonacci(n: int) -> int",
    passed: 5,
    total: 5,
    score: 1.0,
    failing_tests: [],
    snippet: "def fibonacci(n: int) -> int:\n    if n <= 1:\n        return n\n    return fibonacci(n-1) + fibonacci(n-2)",
    complexity: 4,
    iteration: 1,
    calls_functions: [],
    sig_key: "fibonacci|int|int",
    post_bow: ["fibonacci", "return"],
    duration_ms: 75,
    synthesis_method: "beam_search"
  },
  {
    id: "test-entry-6",
    timestamp: new Date().toISOString(),
    spec_id: "test-spec-6",
    spec_hash: "pqr678",
    func_name: "max_in_list",
    func_signature: "def max_in_list(lst: list) -> int",
    passed: 4,
    total: 4,
    score: 1.0,
    failing_tests: [],
    snippet: "def max_in_list(lst: list) -> int:\n    if not lst:\n        return None\n    max_val = lst[0]\n    for num in lst:\n        if num > max_val:\n            max_val = num\n    return max_val",
    complexity: 5,
    iteration: 1,
    calls_functions: [],
    sig_key: "max_in_list|list|int",
    post_bow: ["max", "list", "return"],
    duration_ms: 55,
    synthesis_method: "beam_search"
  },
  {
    id: "test-entry-7",
    timestamp: new Date().toISOString(),
    spec_id: "test-spec-7",
    spec_hash: "stu901",
    func_name: "is_prime",
    func_signature: "def is_prime(n: int) -> bool",
    passed: 5,
    total: 5,
    score: 1.0,
    failing_tests: [],
    snippet: "def is_prime(n: int) -> bool:\n    if n < 2:\n        return False\n    for i in range(2, int(n**0.5) + 1):\n        if n % i == 0:\n            return False\n    return True",
    complexity: 6,
    iteration: 1,
    calls_functions: [],
    sig_key: "is_prime|int|bool",
    post_bow: ["prime", "return"],
    duration_ms: 65,
    synthesis_method: "beam_search"
  },
  {
    id: "test-entry-8",
    timestamp: new Date().toISOString(),
    spec_id: "test-spec-8",
    spec_hash: "vwx234",
    func_name: "count_vowels",
    func_signature: "def count_vowels(s: str) -> int",
    passed: 4,
    total: 4,
    score: 1.0,
    failing_tests: [],
    snippet: "def count_vowels(s: str) -> int:\n    vowels = 'aeiouAEIOU'\n    return sum(1 for char in s if char in vowels)",
    complexity: 3,
    iteration: 1,
    calls_functions: [],
    sig_key: "count_vowels|str|int",
    post_bow: ["count", "vowels", "return"],
    duration_ms: 48,
    synthesis_method: "beam_search"
  },
  {
    id: "test-entry-9",
    timestamp: new Date().toISOString(),
    spec_id: "test-spec-9",
    spec_hash: "yza567",
    func_name: "gcd",
    func_signature: "def gcd(a: int, b: int) -> int",
    passed: 5,
    total: 5,
    score: 1.0,
    failing_tests: [],
    snippet: "def gcd(a: int, b: int) -> int:\n    while b:\n        a, b = b, a % b\n    return a",
    complexity: 3,
    iteration: 1,
    calls_functions: [],
    sig_key: "gcd|int,int|int",
    post_bow: ["gcd", "return"],
    duration_ms: 52,
    synthesis_method: "beam_search"
  },
  {
    id: "test-entry-10",
    timestamp: new Date().toISOString(),
    spec_id: "test-spec-10",
    spec_hash: "bcd890",
    func_name: "sort_list",
    func_signature: "def sort_list(lst: list) -> list",
    passed: 4,
    total: 4,
    score: 1.0,
    failing_tests: [],
    snippet: "def sort_list(lst: list) -> list:\n    return sorted(lst)",
    complexity: 1,
    iteration: 1,
    calls_functions: [],
    sig_key: "sort_list|list|list",
    post_bow: ["sort", "list", "return"],
    duration_ms: 35,
    synthesis_method: "beam_search"
  }
];

console.log("[Test Corpus] Adding test entries...");
for (const entry of testEntries) {
  corpusStorage.insertEntry(entry);
  console.log(`[Test Corpus] Added: ${entry.func_name}`);
}

console.log("[Test Corpus] Done! Added", testEntries.length, "entries");
corpusStorage.close();
