"""
Test suite for need_futurist_timer_ui Flask application
Generated by Aurora-X
"""

import unittest
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

# Import the Flask app
from need_futurist_timer_ui_app import create_app

class TestFlaskApp(unittest.TestCase):
    def setUp(self):
        """Set up test client"""
        self.app = create_app()
        self.app.config['TESTING'] = True
        self.client = self.app.test_client()
    
    def test_app_exists(self):
        """Test that the app exists"""
        self.assertIsNotNone(self.app)
    
    def test_health_endpoint(self):
        """Test the health check endpoint"""
        response = self.client.get('/api/health')
        self.assertEqual(response.status_code, 200)
        data = response.get_json()
        self.assertIn('status', data)
        self.assertEqual(data['status'], 'healthy')
    
    def test_home_route(self):
        """Test the home route returns successfully"""
        response = self.client.get('/')
        self.assertEqual(response.status_code, 200)
        # Check that HTML is returned
        self.assertIn(b'<!DOCTYPE html>', response.data)

if __name__ == '__main__':
    unittest.main()
