"""
Aurora Live Status API - Auto-generated by Aurora
Provides real-time server status data for dashboard
"""

from __future__ import annotations

def get_live_status():
    """Get current status of all Aurora servers"""
    from http.client import HTTPConnection

    servers = {
        "backend": {"port": 5000, "status": "unknown"},
        "bridge": {"port": 5001, "status": "unknown"},
        "self-learn": {"port": 5002, "status": "unknown"},
        "chat": {"port": 5004, "status": "unknown"},
        "vite": {"port": 5173, "status": "unknown"},
    }

    # Check each server
    for name, info in servers.items():
        try:
            conn = HTTPConnection("127.0.0.1", info["port"], timeout=2)
            conn.request("GET", "/")
            resp = conn.getresponse()
            status_code = resp.status
            resp.read()
            conn.close()

            info["status"] = "online" if status_code in (200, 404) else "offline"
            info["http_code"] = status_code
        except Exception:
            info["status"] = "offline"

    return servers


if __name__ == "__main__":
    import json

    print(json.dumps(get_live_status(), indent=2))
