# Generated by Aurora-X v3 (offline, safe)
# Template not recognized - fixed by Aurora
def palindrome_checker():
    '''Template not recognized.'''
    raise NotImplementedError('No v3 template matched')
