"""
Flask web application: generate a futuristic dark-themed countdown timer with keyboard controls and accessibility notes
Generated by Aurora-X Synthesis Engine
"""

from flask import Flask, jsonify
import os


def create_app() -> Flask:
    """Create and configure the Flask application"""
    app = Flask(__name__)
    app.config['ENV'] = 'development'
    app.config['DEBUG'] = True
    
    @app.route('/')
    def index():
        """Handle / route"""
        return f"<h1>Index Page</h1><p>Route: /</p>"
    
    @app.route('/api/health')
    def health():
        """Health check endpoint"""
        return jsonify({"status": "healthy"})
    
    return app


if __name__ == '__main__':
    app = create_app()
    port = int(os.environ.get('PORT', '5000'))
    print(f"🚀 Flask App starting on http://localhost:{port}")
    app.run(host='0.0.0.0', port=port, debug=True)
